# Travis file for ROS2 Java for Android.
# Version 2

sudo: required

language: android
android:
  components:
    - tools
    - platform-tools

services:
  - docker

env:
  global:
    - HOME_BUILD=$HOME/build
    - HOME_ENV=$HOME/.env
    - ANDROID_SDK_VER=sdk-tools-linux-3859397
    - ANDROID_NDK_VER=android-ndk-r15c
    - ANDROID_SDK_HOME=$HOME_BUILD/.android
    - ANDROID_SDK_ROOT=$HOME_BUILD/$ANDROID_SDK_VER
    - ANDROID_NDK_HOME=$HOME_BUILD/$ANDROID_NDK_VER
    - ANDROID_HOME=$ANDROID_SDK_ROOT
    - ANDROID_VER=android-21
    - ANDROID_GCC=arm-linux-androideabi-clang
    - ANDROID_ABI=armeabi-v7a
    - ROS2WS=$HOME_BUILD/ros2_java_ws
    - ROS2JAVA_PATH=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
    - PYTHON_PATH=/usr/bin/python3
    - ROOT_PATH="$HOME_BUILD/ament_ws/install_isolated;$ROS2WS/install_isolated"
    - COMMIT=${TRAVIS_COMMIT::8}
    - PATH="$PATH:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools"
    - ANDROID_PACKAGES="add-ons;addon-google_apis-google-24:build-tools;26.0.1:cmake;3.6.4111459:extras;android;gapid;3:extras;android;m2repository:extras;google;auto:extras;google;m2repository:extras;google;market_apk_expansion:extras;google;market_licensing:extras;google;simulators:extras;google;webdriver:extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2:extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2:lldb;2.3:patcher;v4:platforms;android-21:tools:platform-tools:system-images;android-21;default;armeabi-v7a:emulator"

before_install:
  - ./scripts/travis-ci/android_prepare.sh

script:
  - ./scripts/travis-ci/android_run.sh

after_success:
  - ./scripts/travis-ci/android_success.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4aac82b42245203edceb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
